name: Daily Commit Bot

on:
  schedule:
    # MÃºltiples horarios (UTC)
    - cron: "15 2 * * *"
    - cron: "42 6 * * *"
    - cron: "10 11 * * *"
    - cron: "55 17 * * *"
    - cron: "05 1 * * *" 
    - cron: "30 4 * * *" 
    - cron: "20 8 * * *" 
    - cron: "45 13 * * *" 
    - cron: "33 19 * * *" 
    - cron: "50 22 * * *"
  workflow_dispatch: # permite ejecutarlo a mano

permissions:
  contents: write

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Modify file
        run: |
          echo "Update: $(date -u)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "JGRoldan"
          git config --global user.email "71336562+JGRoldan@users.noreply.github.com"
          git add .
          git commit -m "Automated daily update" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
